-- Motorista
--     ID,NOME,LAT,LONG,DATETIME,TIPO=['ATUALIZACAO_POSICAO', 'ACEITAR_CORRIDA', 'CANCELAR_CORRIDA', 'EMBARQUE_PASSAGEIRO', 'CHEGADA_AO_DESTINO']
CREATE STREAM EVENTOS_MOTORISTA (
    CATEGORIA VARCHAR,
    ID_MOT int,
    NOME VARCHAR,
    LAT DOUBLE,
    LONG DOUBLE,
    DATETIME TIMESTAMP,
    TIPO VARCHAR
) WITH (
    KAFKA_TOPIC = 'EVENTOS_MOTORISTA',
    PARTITIONS = 1,
    VALUE_FORMAT = 'AVRO'
);
INSERT INTO EVENTOS_MOTORISTA VALUES ('MOT', 1, 'JULIO CESAR DA SILVA PEREIRA', -22.850890, -43.252030, FROM_UNIXTIME(UNIX_TIMESTAMP()), 'ATUALIZACAO_POSICAO');
INSERT INTO EVENTOS_MOTORISTA VALUES ('MOT', 2,'NILTON DINIZ', -22.112350, -43.192320, FROM_UNIXTIME(UNIX_TIMESTAMP()), 'ATUALIZACAO_POSICAO');

{
    "categoria": "MOT",
    "id_mot": 1,
    "nome": "Nilton Diniz",
    "lat": -22.850890,
    "long": -43.252030,
    "datetime", "2021-08-23 00:00:00",
    "tipo": "ATUALIZA_POSICAO"
}

-- Passageiro
--     ID,NOME,LAT_ORIG,LONG_ORIG,LAT_DEST,LONG_DEST,DATETIME,TIPO=['SOLICITACAO_CORRIDA', 'CANCELAR_CORRIDA']
CREATE STREAM EVENTOS_PASSAGEIRO (
    ID_PASS int,
    NOME VARCHAR,
    LAT_ORIG DOUBLE,
    LONG_ORIG DOUBLE,
    LAT_DEST DOUBLE,
    LONG_DEST DOUBLE,
    DATETIME TIMESTAMP,
    TIPO VARCHAR
) WITH (
    KAFKA_TOPIC = 'EVENTOS_PASSAGEIRO',
    PARTITIONS = 1,
    VALUE_FORMAT = 'AVRO'
);
-- STATUS=['ABERTA', 'EM ANDAMENTO', 'CANCELADA', 'FINALIZADA']
CREATE STREAM CORRIDA (
    ID_PASS int,
    ID_MOT int,
    LAT_ORIG DOUBLE,
    LONG_ORIG DOUBLE,
    LAT_DEST DOUBLE,
    LONG_DEST DOUBLE,
    DATETIME TIMESTAMP,
    STATUS VARCHAR,
    EXPECT VARCHAR
) WITH (
    KAFKA_TOPIC = 'CORRIDA',
    PARTITIONS = 1,
    VALUE_FORMAT = 'AVRO'
);
    
INSERT INTO EVENTOS_PASSAGEIRO VALUES (123, 'FULANO DE TAL', -22.951972, -43.173834, -22.948356, -43.164403, FROM_UNIXTIME(UNIX_TIMESTAMP()), 'SOLICITACAO_CORRIDA');
INSERT INTO CORRIDA 
SELECT
    ID_PASS,
    0 AS ID_MOT,
    LAT_ORIG,
    LONG_ORIG,
    LAT_DEST,
    LONG_DEST,
    DATETIME,
    'ABERTA' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_PASSAGEIRO
WHERE
    TIPO = 'SOLICITACAO_CORRIDA'
EMIT CHANGES;


INSERT INTO CORRIDA 
SELECT
    0 AS ID_PASS,
    ID_MOT,
    LAT AS LAT_ORIG,
    LONG AS LONG_ORIG,
    LAT AS LAT_DEST,
    LONG AS LONG_DEST,
    DATETIME,
    'EM ANDAMENTO' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_MOTORISTA
WHERE
    TIPO = 'ACEITAR_CORRIDA'
EMIT CHANGES;

INSERT INTO CORRIDA 
SELECT
    0 AS ID_PASS,
    ID_MOT,
    LAT AS LAT_ORIG,
    LONG AS LONG_ORIG,
    LAT AS LAT_DEST,
    LONG AS LONG_DEST,
    DATETIME,
    'FINALIZADA' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_MOTORISTA
WHERE
    TIPO = 'CHEGADA_AO_DESTINO'
EMIT CHANGES;

INSERT INTO CORRIDA 
SELECT
    0 AS ID_PASS,
    ID_MOT,
    LAT AS LAT_ORIG,
    LONG AS LONG_ORIG,
    LAT AS LAT_DEST,
    LONG AS LONG_DEST,
    DATETIME,
    'CANCELADA' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_MOTORISTA
WHERE
    TIPO = 'CANCELAR_CORRIDA'
EMIT CHANGES;


CREATE TABLE EVENTOS_MOTORISTA_CORRIDA AS 
SELECT LATEST_BY_OFFSET(em.categoria) as categoria, 
LATEST_BY_OFFSET(em.ID_MOT) as id_mot,
LATEST_BY_OFFSET(em.NOME) as nome,
LATEST_BY_OFFSET(em.LAT) as lat,
LATEST_BY_OFFSET(em.LONG)as long,
cast(em.DATETIME as varchar) as datetime,
'AGUARDANDO_ACEITE' AS TIPO
 FROM CORRIDA c
FULL OUTER JOIN EVENTOS_MOTORISTA em WITHIN 1 days ON c.expect = em.categoria
WHERE em.tipo = 'ATUALIZACAO_POSICAO' and GEO_DISTANCE(em.lat, em.long, c.lat_orig, c.long_orig) <= 15
group by cast(em.datetime as varchar)
emit changes;