Rode as queries no Control-Center

--1- EVENTOS_MOTORISTA
CREATE STREAM EVENTOS_MOTORISTA (
    CATEGORIA VARCHAR,
    ID_MOT int,
    NOME VARCHAR,
    LAT DOUBLE,
    LONG DOUBLE,
    DATETIME TIMESTAMP,
    TIPO VARCHAR
) WITH (
    KAFKA_TOPIC = 'EVENTOS_MOTORISTA',
    PARTITIONS = 1,
    VALUE_FORMAT = 'JSON'
);

--2- EVENTOS_PASSAGEIRO
CREATE STREAM EVENTOS_PASSAGEIRO (
    ID_PASS int,
    NOME VARCHAR,
    LAT_ORIG DOUBLE,
    LONG_ORIG DOUBLE,
    LAT_DEST DOUBLE,
    LONG_DEST DOUBLE,
    DATETIME TIMESTAMP,
    TIPO VARCHAR
) WITH (
    KAFKA_TOPIC = 'EVENTOS_PASSAGEIRO',
    PARTITIONS = 1,
    VALUE_FORMAT = 'JSON'
);

--3- CORRIDA
CREATE STREAM CORRIDA (
    ID_PASS int,
    ID_MOT int,
    LAT_ORIG DOUBLE,
    LONG_ORIG DOUBLE,
    LAT_DEST DOUBLE,
    LONG_DEST DOUBLE,
    DATETIME TIMESTAMP,
    STATUS VARCHAR,
    EXPECT VARCHAR
) WITH (
    KAFKA_TOPIC = 'CORRIDA',
    PARTITIONS = 1,
    VALUE_FORMAT = 'JSON'
);

--4- INSERIR EM CORRIDA SOLICITAÇÕES DE CORRIDA DO EVENTOS_PASSAGEIRO
INSERT INTO CORRIDA 
SELECT
    ID_PASS,
    0 AS ID_MOT,
    LAT_ORIG,
    LONG_ORIG,
    LAT_DEST,
    LONG_DEST,
    DATETIME,
    'ABERTA' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_PASSAGEIRO
WHERE
    TIPO = 'SOLICITACAO_CORRIDA'
EMIT CHANGES;

--5- INSERIR EM CORRIDA EVENTOS DE ACEITE DO EVENTOS_MOTORISTA
INSERT INTO CORRIDA 
SELECT
    0 AS ID_PASS,
    ID_MOT,
    LAT AS LAT_ORIG,
    LONG AS LONG_ORIG,
    LAT AS LAT_DEST,
    LONG AS LONG_DEST,
    DATETIME,
    'EM ANDAMENTO' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_MOTORISTA
WHERE
    TIPO = 'ACEITAR_CORRIDA'
EMIT CHANGES;

--6- INSERIR EM CORRIDA EVENTOS DE CHEGADA AO DESTINO DO EVENTOS_MOTORISTA
INSERT INTO CORRIDA 
SELECT
    0 AS ID_PASS,
    ID_MOT,
    LAT AS LAT_ORIG,
    LONG AS LONG_ORIG,
    LAT AS LAT_DEST,
    LONG AS LONG_DEST,
    DATETIME,
    'FINALIZADA' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_MOTORISTA
WHERE
    TIPO = 'CHEGADA_AO_DESTINO'
EMIT CHANGES;

--7- INSERIR EM CORRIDA EVENTOS DE CANCELAMENTO DO EVENTOS_MOTORISTA
INSERT INTO CORRIDA 
SELECT
    0 AS ID_PASS,
    ID_MOT,
    LAT AS LAT_ORIG,
    LONG AS LONG_ORIG,
    LAT AS LAT_DEST,
    LONG AS LONG_DEST,
    DATETIME,
    'CANCELADA' AS STATUS,
    'MOT' as EXPECT
FROM
    EVENTOS_MOTORISTA
WHERE
    TIPO = 'CANCELAR_CORRIDA'
EMIT CHANGES;

--8- TABELA PARA NOTIFICAR MOTORISTA CHEGADA DE SOLICITACAO DE CORRIDA
CREATE TABLE EVENTOS_MOTORISTA_CORRIDA WITH (
    VALUE_FORMAT = 'JSON'
) AS
SELECT LATEST_BY_OFFSET(em.categoria) as categoria, 
LATEST_BY_OFFSET(em.ID_MOT) as id_mot,
LATEST_BY_OFFSET(em.NOME) as nome,
LATEST_BY_OFFSET(em.LAT) as lat,
LATEST_BY_OFFSET(em.LONG)as long,
cast(em.DATETIME as varchar) as datetime,
'AGUARDANDO_ACEITE' AS TIPO
 FROM CORRIDA c
FULL OUTER JOIN EVENTOS_MOTORISTA em WITHIN 1 days ON c.expect = em.categoria
WHERE em.tipo = 'ATUALIZACAO_POSICAO' and GEO_DISTANCE(em.lat, em.long, c.lat_orig, c.long_orig) <= 15
group by cast(em.datetime as varchar)
emit changes;